### ISSUE TITLE
Conversion to flowchart

### ISSUE THREAD

**Issue by alexkarargyris** [google-research/tuning_playbook#19]
From a best practices perspective and for better integration with other tools it would be great to see this document convert to a flowchart, if possible.

**Comment by varungodbole** [comment]
Thanks for the feedback! We actually considered making a flowchart for this. But it was difficult because the procedure involves nested loops. I'm personally not sure that I can make a flowchart that is both easy to read and sufficiently complete.

If you feel comfortable taking a stab at it, perhaps we can discuss it offline? But I want to be mindful of your time, since we're trying to be very thoughtful about what we merge with the main brain of this repo.
