### ISSUE TITLE
Many picture links expired.

### ISSUE THREAD

**Issue by cookielovesdata** [google-research/tuning_playbook#60]
Many picture links expired.

**Comment by emergenz** [comment]
To be specific, the ones under [How can optimization failures be debugged and mitigated?](https://github.com/google-research/tuning_playbook#how-can-optimization-failures-be-debugged-and-mitigated)

**Comment by varungodbole** [comment]
Sorry for the delay, and thank you for reporting this!!

It looks like the relative URLs might be broken? I'm not really sure why they're not working, especially since they used to. Out of expediency, I've mailed out [a PR](https://github.com/google-research/tuning_playbook/pull/64) to convert all image URLs to absolute URLs.
