### ISSUE TITLE
Provide (open source) scripts for visualizations in the playbook

### ISSUE THREAD

**Issue by fzyzcjy** [google-research/tuning_playbook#66]
Hi, thanks for the guidance! As is suggested in the playbook, it would be great to automatically generate all these plots. I am happy to make one (looks like just some simple jupyter notebook) if nobody has made an open source one yet.

**Comment by varungodbole** [comment]
Hi @fzyzcjy, thanks for the suggestion! We're trying to keep this repository text-only. Especially since there are many different libraries that one could use to make the relevant plots.

But you're welcome to create another repository with the code samples and add a URL in there to this repo. Or you're welcome to fork this repo and make a self-contained repo.
